name: Build and Export Dist

on:
  push:
    branches: ["master"]  # 触发分支（默认 main/master）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Fix config typo
        run: mv tslin.json tslint.json  # 修复拼写错误（原问题中的 tslin.json）

      - name: Build project
        run: npm run build  # 生成 dist 目录

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-build-output
          path: ./dist  # 上传 dist 目录
